name: Docker build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen
        run: docker build -t xxlilmonkeyy/node-test:latest .

      - name: Subir imagen a Docker Hub
        run: docker push xxlilmonkeyy/node-test:latest